### ISSUE TITLE
0.5.2 amd64 binary crashes following links (XUbuntu 20.04.3 LTS)

### ISSUE THREAD

**Issue by stacksmith** [omar-polo/telescope#3] opened 2021-09-20 14:45 UTC
First time around, hitting enter on the link to Project Gemini crashed out, leaving the terminal in a weird state.

Second time (can't remember which link), also crashed.

Third time telescope started with the `# Oops` document.  Clicking on the email results in `# unknown protocol` screen.

**Comment by omar-polo** [comment] 2021-09-20 15:34
Thanks for spotting it.  I can reproduce on fedora.  The weird thing is that the problem only affects the precompiled binary: on the same fedora installation if I recompile the 0.5.2 I can't reproduce the error.

The "Opps" page (about:crashed) is showed when telescope detects a previous crash.

The "Unknown protocol" page is expected.  Telescope can't (at the moment) handle `mailto:` URLs.  It should use xdg-open probably.

**Comment by stacksmith** [comment] 2021-09-20 15:46
Crashes while following link to Project Gemini from `about:help` (on the bottom), but...

Does not crash following link to Project Gemini from the telescope homepage...

**Comment by omar-polo** [comment] 2021-09-20 16:23
using the precompiled binary I can trigger the bug (sometimes) also by going forward and backward in the history, something that it doesn't seem to happen using a locally compiled binary... I'll re-do the vm where I produce those binaries and test them more.

P.S.: to restore the terminal state, type "reset" (without quotes) and then press enter.

**Comment by stacksmith** [comment] 2021-09-20 18:31
Thanks.  I've browsed around a bit, and it seems mostly ok...  I will have to bite the bullet and install libtls and compile it myself, I suppose.

**Comment by omar-polo** [comment] 2022-01-13 23:34
Just for the record, I had some issues while preparing the precompiled binaries for the just released 0.7.  I've found a possible issue with how I was compiling the browser, libtls and autoconf (libtls contains some symbols for functions that autoconf was checking) that causes some issue during my tests.  I've solved the issue, and hopefully it was the same you spotted, so I'm closing this issue for now.

If there are still problems don't wait to re-open the issue!  I've left the debugging info this time, so that we can find out the problem if it's still present :)

**Closed by omar-polo** 2022-01-13 23:34 UTC
